config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get '/user/auth/failure'=>'omniauth_callbacks#failure'
    post '/finish_registration'=>'omniauth_callbacks#finish_registration'
  end

  root 'questions#index'
  concern :voteable do
    member do
      post 'vote_plus'
      post 'vote_minus'
      post 'devote'
     end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: [:voteable, :commentable] do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:voteable, :commentable] do
      patch :makebest, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable

	has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  scope :last_day_questions, -> { where(created_at: 1.day.ago.all_day) }

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments,
          reject_if: proc{ |param| param[:file].blank? },
          allow_destroy: true

  scope :created_yesterday, -> { where(created_at: Time.current.yesterday.all_day) }
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    #http://localhost:3000/api/v1/questions.json?
    @questions = Question.all
    respond_with @questions #respond_with @questions.to_json(include: :answers)
  end

  def show
    #http://localhost:3000/api/v1/questions/<id>.json?access_token=
    @question = Question.find(params[:id])
    respond_with @question
  end

  #http://localhost:3000/api/v1/questions?access_token=<..>&question[title]='<..>'&question[body]='<..>'
  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question
  end

  private
    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include VoteableController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :load_subscription, only: [:show]
  before_action :check_author, only: [:edit, :destroy]
  before_action :build_answer, only: :show
  before_action :build_attachments, only: [:edit,:show]


  authorize_resource

  def index
    respond_with @questions = Question.all
  end

  def show
    respond_with @question
  end

  def new
    respond_with @question = Question.new
  end

  def edit
  end

  def create
    respond_with @question = current_user.questions.create(question_params)
  end

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user) || Subscription.new
  end

  def update
    @question.update question_params
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private
      def find_question
        @question = Question.find(params[:id])
      end
      def question_params
        params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
      end
      def check_author
        redirect_to :back,
          notice: 'You not author' unless @question.user_id == current_user.id
      end
      def build_answer
        @answer = @question.answers.build
      end
      def build_attachments
        @attachment = @question.attachments ? @question.attachments.any? : @question.attachments.build
      end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.haml
.answer-box{class: "answer-box-id-#{answer.id}"}
  .answer-body
    %p
      =answer.body
      .body-attachments

        - if answer.attachments.any? && answer.user != current_user
          - answer.attachments.each do |attach|
            %li
              =link_to attach.file.filename, attach.file.url

    .answer-best-box{data: {link: makebest_question_answer_path(@question,answer), id: answer.id} }

      -if can?(:update, @question) and answer.best == false and answer.id
        =link_to 'Check as best Answer', makebest_question_answer_path(@question,answer), method: :patch ,class:["best-answer-#{answer.id}"],remote: true
      -if answer.best == true
        %span{class:["this-best-answer-#{answer.id}"]}
          Best Answer
    .votes_block
      = render partial: 'votes/votes_block', locals: { voted_object: answer }
  -if can?(:update, answer)
    -unless answer.body.empty?
      .btn-group
        =link_to 'Remove My Answer', [@question, answer], method: :delete, data: {confirm: "Are you sure?"},remote: true
        =link_to 'Edit My Answer', '', data: {answer_id: answer.id}, class:["edit-answer-link"]
        .attachments-answer
          - if answer.attachments.any?
            - answer.attachments.each do |attach|
              %li
                .field
                =link_to attach.file.filename, attach.file.url



      .answer-edit-form
        = render 'answers/edit', answer: answer
  .comments-list
    %h6
      Comments
    = render 'comments/index', resource: answer, type: "answer"
    - if can?(:create, Comment)
      = render 'comments/form',question: @question, resource: answer, comment: @comment

app/views/questions/_attachment_fields.html.haml
.nested-fields
  .field
    = f.file_field :file
.actions
  = link_to_remove_association "Remove", f, class: "btn btn-default"

app/views/questions/_form.html.haml
- if @question.errors.present?
  - @question.errors.full_messages.each do |message|
    .alert.alert-danger
      =message
.form-group
= bootstrap_form_for([@question])  do |f|
  .field
    = f.text_field :title
  .field
    = f.text_area :body
  #attachments-question
    .field
      = f.fields_for :attachments, @attachment do |attach|
        = render 'attachment_fields', f: attach
    .links
      = link_to_add_association 'Add', f, :attachments,
        partial: 'attachment_fields', class: "btn btn-default"
  .actions
    =f.submit class: "btn btn-default"

app/views/questions/_question.html.haml
.panel.panel-default
  .panel-heading
    %h3
      =link_to question.title, question_path(question)
  .panel-body
    =question.body
  .panel-footer
    .btn.btn-defult
      = 'Автор вопроса: ' + question.user.email

app/views/questions/edit.html.haml
%h1
  Edit your question
=render 'form'
=link_to 'To index', questions_path

app/views/questions/index.html.haml
.questions-list
  -@questions.each do |q|
    =render 'question', question: q


= subscribe_to "/questions"

app/views/questions/new.html.haml
%h1
  New question
=render 'form'

app/views/questions/show.html.haml
.panel.panel-default
  .question
    .panel-heading
      %h3
        = @question.title
    .panel-body
      = @question.body
    .panel-footer
      .question-attach
        = render 'layouts/attachments', attachments: @question.attachments
      .votes_block
        = render partial: 'votes/votes_block', locals: { voted_object: @question }

      =link_to 'To index', questions_path, class:['btn','btn-default']
      = render 'subscriptions/subscription', question: @question
      -if can?(:update, @question)
        .btn-group
          =link_to 'Edit question', edit_question_path(@question), class:['btn','btn-default']
          =link_to 'Delete', @question, method: :delete, data: {confirm: "Are you sure?"}, class:['btn','btn-default']

    .comments-list
      %h6
        Comments
      = render 'comments/index', resource: @question
      - if can?(:create, Comment)
        = render 'comments/form', resource: @question, comment: @question.comments.build


%h4
  Answers:
.add-answer-form-error
= bootstrap_form_for [@question, @question.answers.build], remote: true  do |f|
  = f.text_area :body, label: 'Your answer text:'
  .field
    = f.fields_for :attachments, @answer.attachments.build do |attach|
      = render 'attachment_fields', f: attach
    .links
      = link_to_add_association 'Add', f, :attachments,
        partial: 'attachment_fields', class: "btn btn-default"
  = f.submit 'Add answer'


.answers
  -@question.answers.each do |answer|
    - if answer.persisted?
      =render 'answer', answer: answer
      = subscribe_to "/question/#{answer.id}/comments"

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/question/#{@question.id}/comments"