config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get '/user/auth/failure'=>'omniauth_callbacks#failure'
    post '/finish_registration'=>'omniauth_callbacks#finish_registration'
  end

  root 'questions#index'
  concern :voteable do
    member do
      post 'vote_plus'
      post 'vote_minus'
      post 'devote'
     end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: [:voteable, :commentable] do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:voteable, :commentable] do
      patch :makebest, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates :value, :user_id, :voteable_id, presence: true
  validates :value, numericality: true
  validates :user_id, uniqueness: { scope: [:voteable_id, :voteable_type]}
end

app/views/votes/_votes_block.html.haml
= "Votes #{voted_object.votes_calc}"
- if can?(:vote,voted_object)
    - if voted_object.kind_of?(Question)
        - if voted_object.exists?(current_user)
            =  link_to "Your vote: #{voted_object.get_vote_value(current_user)}, removes vote?", devote_question_path(voted_object), remote: true, method: :post, class: 'btn btn-default btn-devote question-devote-link'
        - else
            = link_to '+', vote_plus_question_path(voted_object), remote: true, method: :post, class: 'btn btn-default btn-vote question-like-link'
            = link_to '-', vote_minus_question_path(voted_object), remote: true, method: :post, class: 'btn btn-default btn-vote question-dislike-link'
    - else
        - if voted_object.exists?(current_user)
            =  link_to "Your vote: #{voted_object.get_vote_value(current_user)}, remove vote?", devote_question_answer_path(voted_object.question, voted_object), remote: true, method: :post, class: 'btn btn-default btn-devote answer-devote-link'
        - else
            = link_to '+', vote_plus_question_answer_path(voted_object.question, voted_object), remote: true, method: :post, class: 'btn btn-default btn-vote answer-like-link'
            = link_to '-', vote_minus_question_answer_path(voted_object.question, voted_object), remote: true, method: :post, class: 'btn btn-default btn-vote answer-dislike-link'